### ISSUE TITLE
3代电池信息 dts 文件位置？

### ISSUE THREAD

**Issue by hellobbn** [lzghzr/mark2_4500#1]
您好，我想询问一下3代的电池文件在哪一个文件里？我找了一下 [sonyxperidev/kernel](https://github.com/sonyxperiadev/kernel/tree/aosp/LA.UM.9.14.r1/arch/arm64/boot/dts/somc) 似乎没有找到。。

**Comment by lzghzr** [comment]
https://github.com/sonyxperiadev/kernel/blob/aosp/LA.UM.9.14.r1/arch/arm64/boot/dts/somc/qg-batterydata-pdx213-tdk-4450mv.dtsi

**Comment by hellobbn** [comment]
`qcom,fg-profile-data` is different in pdx203 and pdx206, for example:
https://github.com/lzghzr/mark2_4500/blob/main/dts/overlay_pdx203.dts#L40
should be
https://github.com/sonyxperiadev/kernel/blob/aosp/LA.UM.9.14.r1/arch/arm64/boot/dts/somc/fg-gen4-batterydata-pdx203-tdk-4400mv.dtsi#L53
For edo

**Comment by lzghzr** [comment]
> `qcom,fg-profile-data` is different in pdx203 and pdx206, for example: https://github.com/lzghzr/mark2_4500/blob/main/dts/overlay_pdx203.dts#L40 should be https://github.com/sonyxperiadev/kernel/blob/aosp/LA.UM.9.14.r1/arch/arm64/boot/dts/somc/fg-gen4-batterydata-pdx203-tdk-4400mv.dtsi#L53 For edo

是的，实际上，模块中pdx206的 `qcom,fg-profile-data` 使用的是原pdx203的内容，而pdx203使用的是pdx206的。
这样做的目的是使内核重新读写 `sram`，这其中包含了电池容量，也就是 `qcom,fg-profile-data` 最后4字节。
事实上，内核只读取 `qcom,fg-profile-data` 前16字节用作校验，但我不知道这16字节的具体作用，所以就pdx203和pdx206的互换了

**Comment by hellobbn** [comment]
https://github.com/hellobbn/android_kernel_sony_sm8250/blob/9dfacc9834233bd76a7a2e60cca42e9805bc8655/drivers/power/supply/qcom/qpnp-fg-gen4.c#L2655 是这个位置吗，通过这一部分检验 profile 是否已经被加载？

**Comment by lzghzr** [comment]
> https://github.com/hellobbn/android_kernel_sony_sm8250/blob/9dfacc9834233bd76a7a2e60cca42e9805bc8655/drivers/power/supply/qcom/qpnp-fg-gen4.c#L2655 是这个位置吗，通过这一部分检验 profile 是否已经被加载？

是的

**Comment by hellobbn** [comment]
好的，谢谢了。
