### ISSUE TITLE
请问关机时，模块是否也有效？

### ISSUE THREAD

**Issue by nagae-memooff** [lzghzr/mark2_4500#2]
我不太懂安卓开发和硬件的东西，但根据我有限的知识和对代码的有限理解， 在刷入这个模块后，因为是修改了dtbo分区里面的数据，而不是修改的运行时，所以只要模块一直在、没重新刷新系统或者其他可能覆盖dtbo分区的操作的话，那么不管关机开机充电，这个模块都应该有效果。我的理解是否正确呢？

**Comment by lzghzr** [comment]
关机时模块确实也生效，但充电的时候好像并不会读取dtbo分区，这个我没测试过

**Comment by nagae-memooff** [comment]
谢谢，那我晚些测试一下开机和关机的充电功率，如果有新发现会贴到这里供参考。

**Comment by nagae-memooff** [comment]
还想了解一下， 我发现 dts/overlay_pdx206.dts 文件里，充电电流的定义是：
qcom,fastchg-current-ma = <3500>;

但dts/origin_pdx206.dts里的定义是：
qcom,fastchg-current-ma = <0xf0a>;
也就是3850毫安，看起来您的模块将充电电流调低了，请问这个有什么原因吗？ 是三代电池的数字本身就这样，还是有什么特定的原因？

**Comment by lzghzr** [comment]
> 还想了解一下， 我发现 dts/overlay_pdx206.dts 文件里，充电电流的定义是： qcom,fastchg-current-ma = <3500>;
> 
> 但dts/origin_pdx206.dts里的定义是： qcom,fastchg-current-ma = <0xf0a>; 也就是3850毫安，看起来您的模块将充电电流调低了，请问这个有什么原因吗？ 是三代电池的数字本身就这样，还是有什么特定的原因？

电池应该可以承受更大的电流，但是我只能参考三代的xperia 10，所以数据会比较保守

**Comment by nagae-memooff** [comment]
> 谢谢，那我晚些测试一下开机和关机的充电功率，如果有新发现会贴到这里供参考。

不好意思，回复晚了。
之前我验证了一下，刷了您的模块后，开机时，使用正确的PD充电器和线，从低电量下开机充电，可以达到18W, 此时用USB电流表读出来的结果大约是6.7V、2.7A左右，不同的充电器电压电流会有些许区别，但会升高电压，功率就可以突破15W， 我测试了多个充电器一般都是18W+; 但在同等电量下，关机充电，则只能得到15W的功率， 4.8V 3.15A ，不会升高电压。

虽然手机给电池实际充电不会直接用这个电压，但如果仅仅从功率的角度上来说，似乎刷了您的模块之后，开机充电是会得到更高的速度的。
现实条件所限，我没有验证关机充电的情况下，是否能达到开机充电时一样的4.45V截止电压。
供其他人参考。

**Comment by nagae-memooff** [comment]
但是不知道什么原因，最近几次lineage OTA之后（我用的是lineage 21），我用您的模块，再也得不到15W以上的功率了，不管怎么重新刷入模块，电压电流都只有4.8V 3.15A,换了所有充电器都如此。 只能怀疑是新版本更改了设备定义，导致修补dtbo失效了？ 不过我后来发现我的电池其实截止充电电压只有4.4V， 怕一直用4.45V充电容易出事，后来就没有继续研究这个了。
